# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gradle-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-gradle-app
  template:
    metadata:
      labels:
        app: my-gradle-app
    spec:
      containers:
      - name: my-gradle-app
        image: ob4d4/my-gradle-app:latest
        ports:
        - containerPort: 80
