apiVersion: v1
kind: Service
metadata:
  name: my-gradle-service
spec:
  type: NodePort
  selector:
    app: gradle-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32000  # Pick a number between 30000-32767
