apiVersion: v1
kind: Service
metadata:
  name: my-gradle-service
spec:
  type: LoadBalancer
  selector:
    app: gradle-app  # Make sure this matches your deployment label
  ports:
    - protocol: TCP
      port: 80         # Port exposed publicly
      targetPort: 8080 # Port your app runs on inside the container
