# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-gradle-app
spec:
  selector:
    app: my-gradle-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
